import React from 'react';
import { Box, Container, Grid } from 'theme-ui';
import BlockTitle from 'components/block-title';
import ServiceCard from 'components/cards/service-card';
import Image1 from 'assets/image-1.png';
import Image2 from 'assets/image-2.png';
import Image3 from 'assets/image-3.png';
import Image4 from 'assets/image-4.png';
import Image5 from 'assets/image-5.png';
import Image6 from 'assets/image-6.png';

const SERVICES_DATA = [
  {
    image: Image1,
    text:
      "Trade securities tokens using Decentralized Exchange.",
    heading: 'DEX',
    path: 'https://app.levinswap.org',
  },
  {
    image: Image2,
    text:
      "Lend out securities assets using Aave's cutting edge markets.",
    heading: 'Lending (TBD)',
    path: 'https://app.aave.com/',
  },
  {
    image: Image3,
    text:
    "Borrow against securities using Aave's cutting edge markets.",
    heading: 'Borrowing (TBD)',
    path: 'https://app.aave.com/',
  },
  {
    image: Image4,
    text:
    "Farm more LEVIN by providing liquidity to Levinswap.",
    heading: 'Farming',
    path: 'https://farm.levinswap.org',
  },
  {
    image: Image5,
    text:
    "Stake LEVIN & earn portion of fees generated by DEX.",
    heading: 'Staking',
    path: 'https://stake.levinswap.org',
  },
  {
    image: Image6,
    text:
    "Become part of the ecosystem. One DAO to rule them all.",
    heading: 'DAO (TBD)',
    path: '#',
  },
];
const Services = () => {
  return (
    <Box as="section" id="services" sx={styles.services}>
      <Container>
        <BlockTitle
          title="DeFi Protocols & Products"
          text="New way of experiencing DeFi"
        />
        <Grid sx={styles.grid}>
          {SERVICES_DATA.map(({ image, text, heading, path }, index) => (
            <ServiceCard
              image={image}
              text={text}
              heading={heading}
              path={path}
              key={index}
            />
          ))}
        </Grid>
      </Container>
    </Box>
  );
};

export default Services;

const styles = {
  services: {
    pt: ['80px', null, null, null, '80px', null, '150px'],
  },
  grid: {
    gridGap: '30px',
    gridTemplateColumns: ['1fr', null, null, '1fr 1fr', null, '1fr 1fr 1fr'],
  },
};
