import React from 'react';
import { Box, Container, Grid } from 'theme-ui';
import BlockTitle from 'components/block-title';
import ServiceCard from 'components/cards/service-card';
import serviceImage1 from 'assets/service-1.png';
import serviceImage2 from 'assets/service-2.png';
import serviceImage3 from 'assets/service-3.png';
import serviceImage4 from 'assets/service-4.png';
import serviceImage5 from 'assets/service-5.png';
import serviceImage6 from 'assets/service-6.png';

const SERVICES_DATA = [
  {
    image: serviceImage1,
    text:
      "Trade securities tokens using Decentralized Exchange.",
    heading: 'DEX',
    path: 'https://app.levinswap.org',
  },
  {
    image: serviceImage2,
    text:
      "Lend out securities assets using Aave's cutting edge markets.",
    heading: 'Lending',
    path: 'https://app.aave.com/',
  },
  {
    image: serviceImage3,
    text:
    "Borrow against securities using Aave's cutting edge markets.",
    heading: 'Borrowing',
    path: 'https://app.aave.com/',
  },
  {
    image: serviceImage4,
    text:
    "Farm more LEVIN by providing liquidity to Levinswap.",
    heading: 'Farming',
    path: 'https://farm.levinswap.org',
  },
  {
    image: serviceImage5,
    text:
    "Stake LEVIN & earn portion of fees generated by DEX.",
    heading: 'Staking',
    path: 'https://stake.levinswap.org',
  },
  {
    image: serviceImage6,
    text:
    "Become part of the ecosystem. One DAO to rule them all.",
    heading: 'DAO',
    path: '#',
  },
];
const Services = () => {
  return (
    <Box as="section" id="services" sx={styles.services}>
      <Container>
        <BlockTitle
          title="DeFi Protocols & Products"
          text="New way of experiencing DeFi"
        />
        <Grid sx={styles.grid}>
          {SERVICES_DATA.map(({ image, text, heading, path }, index) => (
            <ServiceCard
              image={image}
              text={text}
              heading={heading}
              path={path}
              key={index}
            />
          ))}
        </Grid>
      </Container>
    </Box>
  );
};

export default Services;

const styles = {
  services: {
    pt: ['80px', null, null, null, '80px', null, '100px'],
  },
  grid: {
    gridGap: '30px',
    gridTemplateColumns: ['1fr', null, null, '1fr 1fr', null, '1fr 1fr 1fr'],
  },
};
